//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccsEco.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcceecoEntities : DbContext
    {
        public AcceecoEntities()
            : base("name=AcceecoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<CommandeDtrail> CommandeDtrail { get; set; }
        public virtual DbSet<ImageProduit> ImageProduit { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<transport> transport { get; set; }
        public virtual DbSet<UtilisateurSite> UtilisateurSite { get; set; }
    }
}
