//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccsEco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandeDtrail
    {
        public int IDcommandedetail { get; set; }
        public Nullable<int> IDcommande { get; set; }
        public Nullable<int> IDproduit { get; set; }
        public Nullable<System.DateTime> dateCommande { get; set; }
        public Nullable<int> Qte { get; set; }
        public Nullable<int> IdTransport { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual transport transport { get; set; }
    }
}
