//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccsEco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.CommandeDtrail = new HashSet<CommandeDtrail>();
        }
    
        public int IDcommande { get; set; }
        public Nullable<int> IDuser { get; set; }
        public Nullable<System.DateTime> Datecommande { get; set; }
        public string Etat { get; set; }
        public Nullable<int> IDtransport { get; set; }
    
        public virtual transport transport { get; set; }
        public virtual UtilisateurSite UtilisateurSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommandeDtrail> CommandeDtrail { get; set; }
    }
}
