//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccsEco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.CommandeDtrail = new HashSet<CommandeDtrail>();
            this.ImageProduit = new HashSet<ImageProduit>();
        }
    
        public int IDProduit { get; set; }
        public string desegnation { get; set; }
        public string DescriptionProduit { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<int> qte { get; set; }
        public Nullable<double> Prixbarre { get; set; }
        public string categorie { get; set; }
        public string codebar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommandeDtrail> CommandeDtrail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProduit> ImageProduit { get; set; }
    }
}
